/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MeetTheTeamRouteImport } from './routes/meet-the-team'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminSectionsRouteImport } from './routes/admin/sections'
import { Route as AdminPortfolioRouteImport } from './routes/admin/portfolio'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'

const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetTheTeamRoute = MeetTheTeamRouteImport.update({
  id: '/meet-the-team',
  path: '/meet-the-team',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionsRoute = AdminSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfolioRoute = AdminPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/meet-the-team': typeof MeetTheTeamRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/weddings': typeof WeddingsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/meet-the-team': typeof MeetTheTeamRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/weddings': typeof WeddingsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/meet-the-team': typeof MeetTheTeamRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/weddings': typeof WeddingsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/corporate'
    | '/meet-the-team'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/testimonials'
    | '/weddings'
    | '/admin/inquiries'
    | '/admin/portfolio'
    | '/admin/sections'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/corporate'
    | '/meet-the-team'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/testimonials'
    | '/weddings'
    | '/admin/inquiries'
    | '/admin/portfolio'
    | '/admin/sections'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/corporate'
    | '/meet-the-team'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/testimonials'
    | '/weddings'
    | '/admin/inquiries'
    | '/admin/portfolio'
    | '/admin/sections'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  MeetTheTeamRoute: typeof MeetTheTeamRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WeddingsRoute: typeof WeddingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-the-team': {
      id: '/meet-the-team'
      path: '/meet-the-team'
      fullPath: '/meet-the-team'
      preLoaderRoute: typeof MeetTheTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sections': {
      id: '/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AdminSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolio': {
      id: '/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminPortfolioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminPortfolioRoute: typeof AdminPortfolioRoute
  AdminSectionsRoute: typeof AdminSectionsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminPortfolioRoute: AdminPortfolioRoute,
  AdminSectionsRoute: AdminSectionsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  MeetTheTeamRoute: MeetTheTeamRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  WeddingsRoute: WeddingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
